# Form implementation generated from reading ui file 'Penzugyi.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("#BalMenu{\n"
"    background-color:#00FF00;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.BalMenu = QtWidgets.QWidget(parent=self.centralwidget)
        self.BalMenu.setGeometry(QtCore.QRect(0, 0, 171, 611))
        self.BalMenu.setObjectName("BalMenu")
        self.frame = QtWidgets.QFrame(parent=self.BalMenu)
        self.frame.setGeometry(QtCore.QRect(0, 0, 171, 81))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(8, 15, 151, 51))
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(parent=self.BalMenu)
        self.frame_2.setGeometry(QtCore.QRect(0, 60, 171, 511))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(0, 10, 181, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 70, 171, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 120, 171, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 180, 171, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 240, 171, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 300, 171, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 360, 171, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.MainOldal = QtWidgets.QWidget(parent=self.centralwidget)
        self.MainOldal.setGeometry(QtCore.QRect(170, 0, 631, 581))
        self.MainOldal.setObjectName("MainOldal")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.MainOldal)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 621, 561))
        self.stackedWidget.setObjectName("stackedWidget")
        self.KiadasBevetel = QtWidgets.QWidget()
        self.KiadasBevetel.setObjectName("KiadasBevetel")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.KiadasBevetel)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 621, 561))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.EgyszeriKesz = QtWidgets.QPushButton(parent=self.tab)
        self.EgyszeriKesz.setGeometry(QtCore.QRect(20, 250, 75, 24))
        self.EgyszeriKesz.setObjectName("EgyszeriKesz")
        self.EgyszeriOsszeg = QtWidgets.QLineEdit(parent=self.tab)
        self.EgyszeriOsszeg.setGeometry(QtCore.QRect(10, 40, 113, 21))
        self.EgyszeriOsszeg.setObjectName("EgyszeriOsszeg")
        self.EgyszeriPartner = QtWidgets.QLineEdit(parent=self.tab)
        self.EgyszeriPartner.setGeometry(QtCore.QRect(10, 100, 113, 21))
        self.EgyszeriPartner.setObjectName("EgyszeriPartner")
        self.EgyszeriKategoria = QtWidgets.QComboBox(parent=self.tab)
        self.EgyszeriKategoria.setGeometry(QtCore.QRect(20, 170, 168, 22))
        self.EgyszeriKategoria.setObjectName("EgyszeriKategoria")
        self.label_2 = QtWidgets.QLabel(parent=self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 131, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 111, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 101, 16))
        self.label_4.setObjectName("label_4")
        self.EgyszeriBevetel = QtWidgets.QRadioButton(parent=self.tab)
        self.EgyszeriBevetel.setGeometry(QtCore.QRect(10, 210, 89, 20))
        self.EgyszeriBevetel.setObjectName("EgyszeriBevetel")
        self.EgyszeriKiadas = QtWidgets.QRadioButton(parent=self.tab)
        self.EgyszeriKiadas.setGeometry(QtCore.QRect(110, 210, 89, 20))
        self.EgyszeriKiadas.setObjectName("EgyszeriKiadas")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_5 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 131, 16))
        self.label_5.setObjectName("label_5")
        self.RenszeresOsszeg = QtWidgets.QLineEdit(parent=self.tab_2)
        self.RenszeresOsszeg.setGeometry(QtCore.QRect(10, 40, 113, 21))
        self.RenszeresOsszeg.setObjectName("RenszeresOsszeg")
        self.label_7 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 111, 16))
        self.label_7.setObjectName("label_7")
        self.RendszeresPartner = QtWidgets.QLineEdit(parent=self.tab_2)
        self.RendszeresPartner.setGeometry(QtCore.QRect(10, 120, 113, 21))
        self.RendszeresPartner.setObjectName("RendszeresPartner")
        self.label_8 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(10, 170, 101, 16))
        self.label_8.setObjectName("label_8")
        self.RendszeresKategoria = QtWidgets.QComboBox(parent=self.tab_2)
        self.RendszeresKategoria.setGeometry(QtCore.QRect(20, 200, 168, 22))
        self.RendszeresKategoria.setObjectName("RendszeresKategoria")
        self.RendszeresKesz = QtWidgets.QPushButton(parent=self.tab_2)
        self.RendszeresKesz.setGeometry(QtCore.QRect(20, 290, 75, 24))
        self.RendszeresKesz.setObjectName("RendszeresKesz")
        self.RendszeresBevetel = QtWidgets.QRadioButton(parent=self.tab_2)
        self.RendszeresBevetel.setGeometry(QtCore.QRect(20, 250, 89, 20))
        self.RendszeresBevetel.setObjectName("RendszeresBevetel")
        self.RendszeresKiadas = QtWidgets.QRadioButton(parent=self.tab_2)
        self.RendszeresKiadas.setGeometry(QtCore.QRect(120, 250, 89, 20))
        self.RendszeresKiadas.setObjectName("RendszeresKiadas")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.tab_2)
        self.dateEdit.setGeometry(QtCore.QRect(150, 200, 110, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.label_17 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(140, 170, 141, 16))
        self.label_17.setObjectName("label_17")
        self.RendszeresValasztas = QtWidgets.QComboBox(parent=self.tab_2)
        self.RendszeresValasztas.setGeometry(QtCore.QRect(20, 380, 168, 22))
        self.RendszeresValasztas.setObjectName("RendszeresValasztas")
        self.label_18 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(20, 340, 151, 16))
        self.label_18.setObjectName("label_18")
        self.RendszeresTorles = QtWidgets.QPushButton(parent=self.tab_2)
        self.RendszeresTorles.setGeometry(QtCore.QRect(20, 420, 75, 24))
        self.RendszeresTorles.setObjectName("RendszeresTorles")
        self.tabWidget.addTab(self.tab_2, "")
        self.stackedWidget.addWidget(self.KiadasBevetel)
        self.Befektetesek = QtWidgets.QWidget()
        self.Befektetesek.setObjectName("Befektetesek")
        self.BefektetesekOsszeg = QtWidgets.QLineEdit(parent=self.Befektetesek)
        self.BefektetesekOsszeg.setGeometry(QtCore.QRect(20, 40, 113, 21))
        self.BefektetesekOsszeg.setObjectName("BefektetesekOsszeg")
        self.label_6 = QtWidgets.QLabel(parent=self.Befektetesek)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 111, 16))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(parent=self.Befektetesek)
        self.label_9.setGeometry(QtCore.QRect(20, 70, 49, 16))
        self.label_9.setObjectName("label_9")
        
        # Risk level button group
        self.BefektetesekRiskGroup = QtWidgets.QButtonGroup()
        self.BefektetesekAlacsony = QtWidgets.QRadioButton(parent=self.Befektetesek)
        self.BefektetesekAlacsony.setGeometry(QtCore.QRect(20, 100, 89, 20))
        self.BefektetesekAlacsony.setObjectName("BefektetesekAlacsony")
        self.BefektetesekRiskGroup.addButton(self.BefektetesekAlacsony)
        self.BefektetesekKozepes = QtWidgets.QRadioButton(parent=self.Befektetesek)
        self.BefektetesekKozepes.setGeometry(QtCore.QRect(120, 100, 89, 20))
        self.BefektetesekKozepes.setObjectName("BefektetesekKozepes")
        self.BefektetesekRiskGroup.addButton(self.BefektetesekKozepes)
        self.BefektetesekMagas = QtWidgets.QRadioButton(parent=self.Befektetesek)
        self.BefektetesekMagas.setGeometry(QtCore.QRect(220, 100, 89, 20))
        self.BefektetesekMagas.setObjectName("BefektetesekMagas")
        self.BefektetesekRiskGroup.addButton(self.BefektetesekMagas)
        
        self.label_10 = QtWidgets.QLabel(parent=self.Befektetesek)
        self.label_10.setGeometry(QtCore.QRect(20, 130, 49, 16))
        self.label_10.setObjectName("label_10")
        
        # Time period button group
        self.BefektetesekTimeGroup = QtWidgets.QButtonGroup()
        self.BefektetesekRovid = QtWidgets.QRadioButton(parent=self.Befektetesek)
        self.BefektetesekRovid.setGeometry(QtCore.QRect(20, 170, 89, 20))
        self.BefektetesekRovid.setObjectName("BefektetesekRovid")
        self.BefektetesekTimeGroup.addButton(self.BefektetesekRovid)
        self.BefektetesekKozepes2 = QtWidgets.QRadioButton(parent=self.Befektetesek)
        self.BefektetesekKozepes2.setGeometry(QtCore.QRect(120, 170, 89, 20))
        self.BefektetesekKozepes2.setObjectName("BefektetesekKozepes2")
        self.BefektetesekTimeGroup.addButton(self.BefektetesekKozepes2)
        self.BefektetesekHosszu = QtWidgets.QRadioButton(parent=self.Befektetesek)
        self.BefektetesekHosszu.setGeometry(QtCore.QRect(220, 170, 89, 20))
        self.BefektetesekHosszu.setObjectName("BefektetesekHosszu")
        self.BefektetesekTimeGroup.addButton(self.BefektetesekHosszu)
        
        self.BefektetesekKesz = QtWidgets.QPushButton(parent=self.Befektetesek)
        self.BefektetesekKesz.setGeometry(QtCore.QRect(20, 210, 75, 24))
        self.BefektetesekKesz.setObjectName("BefektetesekKesz")
        self.BefektetesekKimenet = QtWidgets.QLabel(parent=self.Befektetesek)
        self.BefektetesekKimenet.setGeometry(QtCore.QRect(20, 250, 580, 300))
        self.BefektetesekKimenet.setObjectName("BefektetesekKimenet")
        self.BefektetesekKimenet.setWordWrap(True)
        self.BefektetesekKimenet.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.stackedWidget.addWidget(self.Befektetesek)
        self.Statisztika = QtWidgets.QWidget()
        self.Statisztika.setObjectName("Statisztika")
        self.stackedWidget.addWidget(self.Statisztika)
        self.Felretetel = QtWidgets.QWidget()
        self.Felretetel.setObjectName("Felretetel")
        self.FelretetelKesz = QtWidgets.QPushButton(parent=self.Felretetel)
        self.FelretetelKesz.setGeometry(QtCore.QRect(0, 70, 75, 24))
        self.FelretetelKesz.setObjectName("FelretetelKesz")
        self.label_12 = QtWidgets.QLabel(parent=self.Felretetel)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 49, 16))
        self.label_12.setObjectName("label_12")
        self.FelretetelOsszeg = QtWidgets.QLineEdit(parent=self.Felretetel)
        self.FelretetelOsszeg.setGeometry(QtCore.QRect(0, 30, 113, 21))
        self.FelretetelOsszeg.setObjectName("FelretetelOsszeg")
        self.FelretetelKategoria = QtWidgets.QComboBox(parent=self.Felretetel)
        self.FelretetelKategoria.setGeometry(QtCore.QRect(10, 110, 168, 22))
        self.FelretetelKategoria.setObjectName("FelretetelKategoria")
        self.FelretetelTorles = QtWidgets.QPushButton(parent=self.Felretetel)
        self.FelretetelTorles.setGeometry(QtCore.QRect(10, 150, 111, 24))
        self.FelretetelTorles.setObjectName("FelretetelTorles")
        self.FelretetelLista = QtWidgets.QListWidget(parent=self.Felretetel)
        self.FelretetelLista.setGeometry(QtCore.QRect(170, 10, 431, 521))
        self.FelretetelLista.setObjectName("FelretetelLista")
        self.stackedWidget.addWidget(self.Felretetel)
        self.MultbeliTranzakciok = QtWidgets.QWidget()
        self.MultbeliTranzakciok.setObjectName("MultbeliTranzakciok")
        self.MultbeliOutput = QtWidgets.QTableView(parent=self.MultbeliTranzakciok)
        self.MultbeliOutput.setGeometry(QtCore.QRect(25, 111, 581, 441))
        self.MultbeliOutput.setObjectName("MultbeliOutput")
        self.MultbeliKesz = QtWidgets.QPushButton(parent=self.MultbeliTranzakciok)
        self.MultbeliKesz.setGeometry(QtCore.QRect(420, 70, 91, 24))
        self.MultbeliKesz.setObjectName("MultbeliKesz")
        self.MultbeliMindent = QtWidgets.QPushButton(parent=self.MultbeliTranzakciok)
        self.MultbeliMindent.setGeometry(QtCore.QRect(520, 70, 91, 24))
        self.MultbeliMindent.setObjectName("MultbeliMindent")
        self.MultbeliKategoria = QtWidgets.QComboBox(parent=self.MultbeliTranzakciok)
        self.MultbeliKategoria.setGeometry(QtCore.QRect(10, 60, 98, 22))
        self.MultbeliKategoria.setObjectName("MultbeliKategoria")
        self.label_13 = QtWidgets.QLabel(parent=self.MultbeliTranzakciok)
        self.label_13.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.label_13.setObjectName("label_13")
        # Date range filters
        self.MultbeliDatumTol = QtWidgets.QDateEdit(parent=self.MultbeliTranzakciok)
        self.MultbeliDatumTol.setGeometry(QtCore.QRect(100, 30, 110, 22))
        self.MultbeliDatumTol.setCalendarPopup(True)
        self.MultbeliDatumTol.setObjectName("MultbeliDatumTol")
        self.MultbeliDatumIg = QtWidgets.QDateEdit(parent=self.MultbeliTranzakciok)
        self.MultbeliDatumIg.setGeometry(QtCore.QRect(100, 60, 110, 22))
        self.MultbeliDatumIg.setCalendarPopup(True)
        self.MultbeliDatumIg.setObjectName("MultbeliDatumIg")
        self.label_14 = QtWidgets.QLabel(parent=self.MultbeliTranzakciok)
        self.label_14.setGeometry(QtCore.QRect(100, 10, 80, 16))
        self.label_14.setObjectName("label_14")
        self.label_14_2 = QtWidgets.QLabel(parent=self.MultbeliTranzakciok)
        self.label_14_2.setGeometry(QtCore.QRect(220, 35, 20, 16))
        self.label_14_2.setObjectName("label_14_2")
        # Amount range filters
        self.label_15 = QtWidgets.QLabel(parent=self.MultbeliTranzakciok)
        self.label_15.setGeometry(QtCore.QRect(250, 10, 80, 16))
        self.label_15.setObjectName("label_15")
        self.MultbeliOsszegMin = QtWidgets.QLineEdit(parent=self.MultbeliTranzakciok)
        self.MultbeliOsszegMin.setGeometry(QtCore.QRect(250, 30, 80, 21))
        self.MultbeliOsszegMin.setObjectName("MultbeliOsszegMin")
        self.MultbeliOsszegMax = QtWidgets.QLineEdit(parent=self.MultbeliTranzakciok)
        self.MultbeliOsszegMax.setGeometry(QtCore.QRect(250, 60, 80, 21))
        self.MultbeliOsszegMax.setObjectName("MultbeliOsszegMax")
        self.label_15_2 = QtWidgets.QLabel(parent=self.MultbeliTranzakciok)
        self.label_15_2.setGeometry(QtCore.QRect(340, 45, 20, 16))
        self.label_15_2.setObjectName("label_15_2")
        # Partner search filter
        self.label_partner = QtWidgets.QLabel(parent=self.MultbeliTranzakciok)
        self.label_partner.setGeometry(QtCore.QRect(370, 10, 80, 16))
        self.label_partner.setObjectName("label_partner")
        self.MultbeliPartner = QtWidgets.QLineEdit(parent=self.MultbeliTranzakciok)
        self.MultbeliPartner.setGeometry(QtCore.QRect(370, 30, 130, 21))
        self.MultbeliPartner.setObjectName("MultbeliPartner")
        self.stackedWidget.addWidget(self.MultbeliTranzakciok)
        self.Kategoriak = QtWidgets.QWidget()
        self.Kategoriak.setObjectName("Kategoriak")
        self.KategoriaKategoria = QtWidgets.QLineEdit(parent=self.Kategoriak)
        self.KategoriaKategoria.setGeometry(QtCore.QRect(20, 40, 113, 21))
        self.KategoriaKategoria.setObjectName("KategoriaKategoria")
        self.label_16 = QtWidgets.QLabel(parent=self.Kategoriak)
        self.label_16.setGeometry(QtCore.QRect(20, 10, 91, 16))
        self.label_16.setObjectName("label_16")
        self.KategoriaKesz = QtWidgets.QPushButton(parent=self.Kategoriak)
        self.KategoriaKesz.setGeometry(QtCore.QRect(30, 80, 75, 24))
        self.KategoriaKesz.setObjectName("KategoriaKesz")
        # Right side - manage existing categories
        self.label_kategoria_valaszt = QtWidgets.QLabel(parent=self.Kategoriak)
        self.label_kategoria_valaszt.setGeometry(QtCore.QRect(250, 10, 150, 16))
        self.label_kategoria_valaszt.setObjectName("label_kategoria_valaszt")
        self.KategoriaValaszt = QtWidgets.QComboBox(parent=self.Kategoriak)
        self.KategoriaValaszt.setGeometry(QtCore.QRect(250, 30, 150, 22))
        self.KategoriaValaszt.setObjectName("KategoriaValaszt")
        self.KategoriaUjNev = QtWidgets.QLineEdit(parent=self.Kategoriak)
        self.KategoriaUjNev.setGeometry(QtCore.QRect(250, 70, 150, 21))
        self.KategoriaUjNev.setObjectName("KategoriaUjNev")
        self.KategoriaAtnevez = QtWidgets.QPushButton(parent=self.Kategoriak)
        self.KategoriaAtnevez.setGeometry(QtCore.QRect(250, 100, 100, 24))
        self.KategoriaAtnevez.setObjectName("KategoriaAtnevez")
        self.KategoriaTorles = QtWidgets.QPushButton(parent=self.Kategoriak)
        self.KategoriaTorles.setGeometry(QtCore.QRect(360, 100, 100, 24))
        self.KategoriaTorles.setObjectName("KategoriaTorles")
        self.stackedWidget.addWidget(self.Kategoriak)
        self.DevizaValtasa = QtWidgets.QWidget()
        self.DevizaValtasa.setObjectName("DevizaValtasa")
        self.label_11 = QtWidgets.QLabel(parent=self.DevizaValtasa)
        self.label_11.setGeometry(QtCore.QRect(20, 10, 49, 16))
        self.label_11.setObjectName("label_11")
        self.DevizaOsszeg = QtWidgets.QLineEdit(parent=self.DevizaValtasa)
        self.DevizaOsszeg.setGeometry(QtCore.QRect(20, 40, 113, 21))
        self.DevizaOsszeg.setObjectName("DevizaOsszeg")
        self.DevizaMibol = QtWidgets.QComboBox(parent=self.DevizaValtasa)
        self.DevizaMibol.setGeometry(QtCore.QRect(200, 10, 68, 22))
        self.DevizaMibol.setObjectName("DevizaMibol")
        self.DevizaMibe = QtWidgets.QComboBox(parent=self.DevizaValtasa)
        self.DevizaMibe.setGeometry(QtCore.QRect(200, 40, 68, 22))
        self.DevizaMibe.setObjectName("DevizaMibe")
        self.DevizaKimenet = QtWidgets.QLabel(parent=self.DevizaValtasa)
        self.DevizaKimenet.setGeometry(QtCore.QRect(200, 80, 300, 50))
        self.DevizaKimenet.setObjectName("DevizaKimenet")
        self.DevizaKimenet.setWordWrap(True)
        self.DevizaKesz = QtWidgets.QPushButton(parent=self.DevizaValtasa)
        self.DevizaKesz.setGeometry(QtCore.QRect(20, 80, 75, 24))
        self.DevizaKesz.setObjectName("DevizaKesz")
        self.stackedWidget.addWidget(self.DevizaValtasa)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Aktuális egyenleg: X Ft"))
        self.pushButton.setText(_translate("MainWindow", "Kiadások/Bevétel"))
        self.pushButton_2.setText(_translate("MainWindow", "Befektetések"))
        self.pushButton_3.setText(_translate("MainWindow", "Statisztika"))
        self.pushButton_4.setText(_translate("MainWindow", "Félretétel"))
        self.pushButton_5.setText(_translate("MainWindow", "Múltbéli tranzakciók"))
        self.pushButton_6.setText(_translate("MainWindow", "Kategóriák"))
        self.pushButton_7.setText(_translate("MainWindow", "Deviza váltása"))
        self.EgyszeriKesz.setText(_translate("MainWindow", "Kész"))
        self.label_2.setText(_translate("MainWindow", "Mekkora összeg?"))
        self.label_3.setText(_translate("MainWindow", "Kinek/kitől érkezik?"))
        self.label_4.setText(_translate("MainWindow", "Milyen kategória?"))
        self.EgyszeriBevetel.setText(_translate("MainWindow", "Bevétel"))
        self.EgyszeriKiadas.setText(_translate("MainWindow", "Kiadás"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Egyszeri"))
        self.label_5.setText(_translate("MainWindow", "Mekkora összeg?"))
        self.label_7.setText(_translate("MainWindow", "Kinek/kitől érkezik?"))
        self.label_8.setText(_translate("MainWindow", "Milyen kategória?"))
        self.RendszeresKesz.setText(_translate("MainWindow", "Kész"))
        self.RendszeresBevetel.setText(_translate("MainWindow", "Bevétel"))
        self.RendszeresKiadas.setText(_translate("MainWindow", "Kiadás"))
        self.label_17.setText(_translate("MainWindow", "Kezdeti dátum"))
        self.label_18.setText(_translate("MainWindow", "Melyiket szeretnéd törölni?"))
        self.RendszeresTorles.setText(_translate("MainWindow", "Törlés"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Rendszeres"))
        self.label_6.setText(_translate("MainWindow", "Befektetési összeg"))
        self.label_9.setText(_translate("MainWindow", "Kockázat"))
        self.BefektetesekAlacsony.setText(_translate("MainWindow", "Alacsony"))
        self.BefektetesekKozepes.setText(_translate("MainWindow", "Közepes"))
        self.BefektetesekMagas.setText(_translate("MainWindow", "Magas"))
        self.BefektetesekRovid.setText(_translate("MainWindow", "Rövid"))
        self.BefektetesekKozepes2.setText(_translate("MainWindow", "Közepes"))
        self.BefektetesekHosszu.setText(_translate("MainWindow", "Hosszú"))
        self.label_10.setText(_translate("MainWindow", "Időtáv"))
        self.BefektetesekKesz.setText(_translate("MainWindow", "Kalkuláció"))
        self.BefektetesekKimenet.setText(_translate("MainWindow", ""))
        self.FelretetelKesz.setText(_translate("MainWindow", "Felvétéel"))
        self.label_12.setText(_translate("MainWindow", "Összeg:"))
        self.FelretetelTorles.setText(_translate("MainWindow", "Félretétel törlése"))
        self.MultbeliKesz.setText(_translate("MainWindow", "Keresés"))
        self.MultbeliMindent.setText(_translate("MainWindow", "Mindent mutat"))
        self.label_13.setText(_translate("MainWindow", "Kategória"))
        self.label_14.setText(_translate("MainWindow", "Dátum"))
        self.label_14_2.setText(_translate("MainWindow", "-"))
        self.label_15.setText(_translate("MainWindow", "Összeg"))
        self.label_15_2.setText(_translate("MainWindow", "-"))
        self.label_partner.setText(_translate("MainWindow", "Partner"))
        self.MultbeliOsszegMin.setPlaceholderText(_translate("MainWindow", "Min"))
        self.MultbeliOsszegMax.setPlaceholderText(_translate("MainWindow", "Max"))
        self.MultbeliPartner.setPlaceholderText(_translate("MainWindow", "Keresés..."))
        self.label_16.setText(_translate("MainWindow", "Új kategória neve"))
        self.KategoriaKesz.setText(_translate("MainWindow", "Hozzáadás"))
        self.label_kategoria_valaszt.setText(_translate("MainWindow", "Kategória kezelése"))
        self.KategoriaUjNev.setPlaceholderText(_translate("MainWindow", "Új név..."))
        self.KategoriaAtnevez.setText(_translate("MainWindow", "Átnevezés"))
        self.KategoriaTorles.setText(_translate("MainWindow", "Törlés"))
        self.label_11.setText(_translate("MainWindow", "Összeg:"))
        self.DevizaKimenet.setText(_translate("MainWindow", "TextLabel"))
        self.DevizaKesz.setText(_translate("MainWindow", "Futtatás"))


if __name__ == "__main__":
    import sys
    import json
    from valutavalto import open_exchange_window
    from statistics_ui import setup_statistics_page
    from db_manager import TransactionManager

    class MainWindow(QtWidgets.QMainWindow):
        def __init__(self):
            super().__init__()
            self.ui = Ui_MainWindow()
            self.ui.setupUi(self)
            
            # Initialize database manager
            self.db_manager = TransactionManager()

            # Update balance from database on startup
            self.update_balance()

            # Bal oldali gombok összekötése a lapozó függvénnyel
            self.ui.pushButton.clicked.connect(lambda: self.lapozas(0))
            self.ui.pushButton_2.clicked.connect(lambda: self.lapozas(1))
            self.ui.pushButton_3.clicked.connect(lambda: self.lapozas(2))
            self.ui.pushButton_4.clicked.connect(lambda: self.lapozas(3))
            self.ui.pushButton_5.clicked.connect(lambda: self.lapozas(4))
            self.ui.pushButton_6.clicked.connect(lambda: self.lapozas(5))
            self.ui.pushButton_7.clicked.connect(lambda: self.lapozas(6))

            # Egyszeri gomb esemény
            self.ui.EgyszeriKesz.clicked.connect(self.egyszeri_kesz_megnyomva)
            
            # Rendszeres gomb esemény
            self.ui.RendszeresKesz.clicked.connect(self.rendszeres_kesz_megnyomva)
            self.ui.RendszeresTorles.clicked.connect(self.rendszeres_torles)
            
            # Load recurring transactions list
            self.load_recurring_list()
            
            # Deviza váltása page elemek beállítása
            self.setup_currency_page()
            self.ui.DevizaKesz.clicked.connect(self.deviza_valt)
            
            # Statisztika page beállítása
            self.stats_widget = setup_statistics_page(self.ui.Statisztika)
            
            # Kategóriák page beállítása
            self.setup_categories_page()
            self.ui.KategoriaKesz.clicked.connect(self.add_category)
            self.ui.KategoriaAtnevez.clicked.connect(self.rename_category)
            self.ui.KategoriaTorles.clicked.connect(self.delete_category)
            # Félretétel buttons and list
            self.ui.FelretetelKesz.clicked.connect(self.add_saving)
            self.ui.FelretetelTorles.clicked.connect(self.delete_saving)
            # Load existing savings into the list
            self.load_savings_list()
            
            # Múltbéli tranzakciók page beállítása
            self.setup_transactions_page()
            self.ui.MultbeliKesz.clicked.connect(self.search_transactions)
            self.ui.MultbeliMindent.clicked.connect(self.show_all_transactions)
            
            # Befektetések page beállítása
            self.ui.BefektetesekKesz.clicked.connect(self.befektetesek_kalkulator)


        # Egyszeri gomb kezelése
        def egyszeri_kesz_megnyomva(self):
            from datetime import date as date_module
            
            osszeg_str = self.ui.EgyszeriOsszeg.text()
            try:
                osszeg = float(osszeg_str) if osszeg_str else 0
            except ValueError:
                QtWidgets.QMessageBox.warning(self, "Hiba", "Érvénytelen összeg!")
                return
            
            partner = self.ui.EgyszeriPartner.text().strip()
            kategoria_name = self.ui.EgyszeriKategoria.currentText()
            
            # Validation
            if not partner:
                QtWidgets.QMessageBox.warning(self, "Hiba", "Kérlek, add meg a partnert!")
                return
            
            if not kategoria_name:
                QtWidgets.QMessageBox.warning(self, "Hiba", "Kérlek, válassz kategóriát!")
                return
            
            # Check if income or expense
            if self.ui.EgyszeriKiadas.isChecked():
                osszeg = -abs(osszeg)  # Expenses are negative
            elif self.ui.EgyszeriBevetel.isChecked():
                osszeg = abs(osszeg)  # Income is positive
            else:
                QtWidgets.QMessageBox.warning(self, "Hiba", "Kérlek, válaszd ki, hogy bevétel vagy kiadás!")
                return
            
            try:
                # Get category object
                categories = self.db_manager.get_all_cat()
                category = next((cat for cat in categories if cat.name == kategoria_name), None)
                
                if not category:
                    QtWidgets.QMessageBox.warning(self, "Hiba", "Kategória nem található!")
                    return
                
                # Add transaction to database
                self.db_manager.add_trans(
                    money=osszeg,
                    from_to=partner,
                    date_=date_module.today(),
                    categories=[category]
                )
                
                # Update balance
                self.update_balance()
                
                # Clear form
                self.ui.EgyszeriOsszeg.clear()
                self.ui.EgyszeriPartner.clear()
                self.ui.EgyszeriBevetel.setChecked(False)
                self.ui.EgyszeriKiadas.setChecked(False)
                
                # Refresh transactions page if it exists
                if hasattr(self, 'transaction_model'):
                    self.load_all_transactions()
                
                # Refresh statistics if it exists
                if hasattr(self, 'stats_widget'):
                    self.stats_widget.update_statistics()
                
                QtWidgets.QMessageBox.information(self, "Siker", "Tranzakció sikeresen hozzáadva!")
                
            except Exception as e:
                QtWidgets.QMessageBox.critical(self, "Hiba", f"Hiba történt: {str(e)}")
        
        def rendszeres_kesz_megnyomva(self):
            """Handle recurring transaction submission - saves as recurring transaction template"""
            from datetime import date as date_module
            
            osszeg_str = self.ui.RenszeresOsszeg.text()
            try:
                osszeg = float(osszeg_str) if osszeg_str else 0
            except ValueError:
                QtWidgets.QMessageBox.warning(self, "Hiba", "Érvénytelen összeg!")
                return
            
            partner = self.ui.RendszeresPartner.text().strip()
            kategoria_name = self.ui.RendszeresKategoria.currentText()
            
            # Validation
            if not partner:
                QtWidgets.QMessageBox.warning(self, "Hiba", "Kérlek, add meg a partnert!")
                return
            
            if not kategoria_name:
                QtWidgets.QMessageBox.warning(self, "Hiba", "Kérlek, válassz kategóriát!")
                return
            
            # Check if income or expense
            if self.ui.RendszeresKiadas.isChecked():
                osszeg = -abs(osszeg)
            elif self.ui.RendszeresBevetel.isChecked():
                osszeg = abs(osszeg)
            else:
                QtWidgets.QMessageBox.warning(self, "Hiba", "Kérlek, válaszd ki, hogy bevétel vagy kiadás!")
                return
            
            try:
                # Get category object
                categories = self.db_manager.get_all_cat()
                category = next((cat for cat in categories if cat.name == kategoria_name), None)
                
                if not category:
                    QtWidgets.QMessageBox.warning(self, "Hiba", "Kategória nem található!")
                    return
                
                # Get the start date from dateEdit
                qdate = self.ui.dateEdit.date()
                start_date = date_module(qdate.year(), qdate.month(), qdate.day())
                
                # Add recurring transaction to database
                self.db_manager.add_recurring_trans(
                    money=osszeg,
                    from_to=partner,
                    start_date=start_date,
                    category=category
                )
                
                # Clear form
                self.ui.RenszeresOsszeg.clear()
                self.ui.RendszeresPartner.clear()
                self.ui.RendszeresBevetel.setChecked(False)
                self.ui.RendszeresKiadas.setChecked(False)
                
                # Reload recurring transactions list
                self.load_recurring_list()
                
                # Refresh statistics if it exists
                if hasattr(self, 'stats_widget'):
                    self.stats_widget.update_statistics()
                
                QtWidgets.QMessageBox.information(self, "Siker", "Rendszeres tranzakció sikeresen hozzáadva!")
                
            except Exception as e:
                QtWidgets.QMessageBox.critical(self, "Hiba", f"Hiba történt: {str(e)}")
        
        def load_recurring_list(self):
            """Load recurring transactions into dropdown"""
            recurring_list = self.db_manager.get_recurring_trans_as_list()
            
            self.ui.RendszeresValasztas.clear()
            
            # Store the IDs separately for later retrieval
            self.recurring_ids = {}
            for rec_id, display_text in recurring_list:
                self.ui.RendszeresValasztas.addItem(display_text)
                self.recurring_ids[display_text] = rec_id
        
        def rendszeres_torles(self):
            """Delete selected recurring transaction"""
            selected_text = self.ui.RendszeresValasztas.currentText()
            
            if not selected_text:
                QtWidgets.QMessageBox.warning(self, "Hiba", "Nincs kiválasztott rendszeres tranzakció!")
                return
            
            # Confirm deletion
            reply = QtWidgets.QMessageBox.question(
                self, 
                'Megerősítés', 
                f"Biztosan törölni szeretnéd ezt a rendszeres tranzakciót?\n{selected_text}",
                QtWidgets.QMessageBox.StandardButton.Yes | QtWidgets.QMessageBox.StandardButton.No,
                QtWidgets.QMessageBox.StandardButton.No
            )
            
            if reply == QtWidgets.QMessageBox.StandardButton.Yes:
                try:
                    # Get the recurring transaction ID
                    rec_id = self.recurring_ids.get(selected_text)
                    
                    if rec_id:
                        # Find and delete the recurring transaction
                        recurring_trans = self.db_manager.get_all_recurring_trans()
                        recurring = next((rt for rt in recurring_trans if rt.id == rec_id), None)
                        
                        if recurring:
                            self.db_manager.del_recurring_trans(recurring)
                            self.load_recurring_list()
                            QtWidgets.QMessageBox.information(self, "Siker", "Rendszeres tranzakció törölve!")
                        else:
                            QtWidgets.QMessageBox.warning(self, "Hiba", "Rendszeres tranzakció nem található!")
                    else:
                        QtWidgets.QMessageBox.warning(self, "Hiba", "Rendszeres tranzakció nem található!")
                except Exception as e:
                    QtWidgets.QMessageBox.critical(self, "Hiba", f"Hiba történt: {str(e)}")
        
        def update_balance(self):
            """Calculate and update the current balance from all transactions"""
            transactions = self.db_manager.get_all_trans()
            balance = sum(trans.money for trans in transactions)
            self.ui.label.setText(f"Aktuális egyenleg: {balance:,.2f} Ft")

        def lapozas(self, index):
            self.ui.stackedWidget.setCurrentIndex(index)

        def setup_currency_page(self):
            """Setup currency exchange page with available currencies"""
            currencies = ["HUF", "USD", "EUR", "GBP", "CHF"]
            
            # Populate combo boxes
            self.ui.DevizaMibol.clear()
            self.ui.DevizaMibe.clear()
            self.ui.DevizaMibol.addItems(currencies)
            self.ui.DevizaMibe.addItems(currencies)
            
            # Set default values
            self.ui.DevizaMibol.setCurrentText("HUF")
            self.ui.DevizaMibe.setCurrentText("EUR")
            
            # Clear output label
            self.ui.DevizaKimenet.setText("")

        def deviza_valt(self):
            """Handle currency exchange calculation"""
            from valutavalto import get_exchange_rate
            
            try:
                amount = float(self.ui.DevizaOsszeg.text())
                from_currency = self.ui.DevizaMibol.currentText()
                to_currency = self.ui.DevizaMibe.currentText()
                
                result, rate = get_exchange_rate(from_currency, to_currency, amount)
                
                if result is not None:
                    output_text = f"{result:.2f} {to_currency}\n(1 {from_currency} = {rate:.4f} {to_currency})"
                    self.ui.DevizaKimenet.setText(output_text)
                    self.ui.DevizaKimenet.setStyleSheet("color: green; font-weight: bold;")
                else:
                    self.ui.DevizaKimenet.setText("Hiba az API hívásban")
                    self.ui.DevizaKimenet.setStyleSheet("color: red;")
                    
            except ValueError:
                self.ui.DevizaKimenet.setText("Érvénytelen összeg!")
                self.ui.DevizaKimenet.setStyleSheet("color: red;")

        def setup_categories_page(self):
            """Setup categories page with existing categories"""
            self.load_categories_list()
        
        def load_categories_list(self):
            """Load all categories into the dropdown and combo boxes"""
            categories = self.db_manager.get_all_cat()
            category_names = [cat.name for cat in categories]
            
            # Update category selection dropdown
            self.ui.KategoriaValaszt.clear()
            self.ui.KategoriaValaszt.addItems(category_names)
            
            # Update all other category dropdowns
            self.ui.EgyszeriKategoria.clear()
            self.ui.EgyszeriKategoria.addItems(category_names)
            
            self.ui.RendszeresKategoria.clear()
            self.ui.RendszeresKategoria.addItems(category_names)
            
            self.ui.FelretetelKategoria.clear()
            self.ui.FelretetelKategoria.addItems(category_names)
            
            self.ui.MultbeliKategoria.clear()
            self.ui.MultbeliKategoria.addItems(category_names)
        
        def add_category(self):
            """Add a new category to the database"""
            category_name = self.ui.KategoriaKategoria.text().strip()
            
            if not category_name:
                QtWidgets.QMessageBox.warning(self, "Hiba", "Kérlek, add meg a kategória nevét!")
                return
            
            try:
                self.db_manager.add_cat(category_name)
                self.load_categories_list()
                self.ui.KategoriaKategoria.clear()
                QtWidgets.QMessageBox.information(self, "Siker", f"A '{category_name}' kategória sikeresen hozzáadva!")
            except Exception as e:
                QtWidgets.QMessageBox.critical(self, "Hiba", f"Hiba történt: {str(e)}")
        
        def delete_category(self):
            """Delete selected category from the database"""
            category_name = self.ui.KategoriaValaszt.currentText()
            
            if not category_name:
                QtWidgets.QMessageBox.warning(self, "Hiba", "Nincs kiválasztott kategória!")
                return
            
            # Confirm deletion
            reply = QtWidgets.QMessageBox.question(
                self, 
                'Megerősítés', 
                f"Biztosan törölni szeretnéd a '{category_name}' kategóriát?",
                QtWidgets.QMessageBox.StandardButton.Yes | QtWidgets.QMessageBox.StandardButton.No,
                QtWidgets.QMessageBox.StandardButton.No
            )
            
            if reply == QtWidgets.QMessageBox.StandardButton.Yes:
                try:
                    # Find the category object
                    categories = self.db_manager.get_all_cat()
                    category = next((cat for cat in categories if cat.name == category_name), None)
                    
                    if category:
                        self.db_manager.del_cat(category)
                        self.load_categories_list()
                        QtWidgets.QMessageBox.information(self, "Siker", f"A '{category_name}' kategória törölve!")
                    else:
                        QtWidgets.QMessageBox.warning(self, "Hiba", "Kategória nem található!")
                except Exception as e:
                    QtWidgets.QMessageBox.critical(self, "Hiba", f"Hiba történt: {str(e)}")
        
        def rename_category(self):
            """Rename selected category in the database"""
            category_name = self.ui.KategoriaValaszt.currentText()
            new_name = self.ui.KategoriaUjNev.text().strip()
            
            if not category_name:
                QtWidgets.QMessageBox.warning(self, "Hiba", "Nincs kiválasztott kategória!")
                return
            
            if not new_name:
                QtWidgets.QMessageBox.warning(self, "Hiba", "Kérlek, add meg az új kategória nevet!")
                return
            
            if category_name == new_name:
                QtWidgets.QMessageBox.warning(self, "Hiba", "Az új név megegyezik a régivel!")
                return
            
            # Check if new name already exists
            categories = self.db_manager.get_all_cat()
            if any(cat.name == new_name for cat in categories):
                QtWidgets.QMessageBox.warning(self, "Hiba", f"A '{new_name}' kategória már létezik!")
                return
            
            # Confirm rename
            reply = QtWidgets.QMessageBox.question(
                self, 
                'Megerősítés', 
                f"Biztosan át szeretnéd nevezni a '{category_name}' kategóriát erre: '{new_name}'?",
                QtWidgets.QMessageBox.StandardButton.Yes | QtWidgets.QMessageBox.StandardButton.No,
                QtWidgets.QMessageBox.StandardButton.No
            )
            
            if reply == QtWidgets.QMessageBox.StandardButton.Yes:
                try:
                    # Find the category object
                    category = next((cat for cat in categories if cat.name == category_name), None)
                    
                    if category:
                        self.db_manager.rename_cat(category, new_name)
                        self.load_categories_list()
                        self.ui.KategoriaUjNev.clear()
                        QtWidgets.QMessageBox.information(self, "Siker", 
                            f"A '{category_name}' kategória sikeresen átnevezve erre: '{new_name}'!")
                    else:
                        QtWidgets.QMessageBox.warning(self, "Hiba", "Kategória nem található!")
                except Exception as e:
                    QtWidgets.QMessageBox.critical(self, "Hiba", f"Hiba történt: {str(e)}")

        def setup_transactions_page(self):
            """Setup past transactions page"""
            from PyQt6.QtGui import QStandardItemModel, QStandardItem
            from datetime import datetime, timedelta
            
            # Create table model
            self.transaction_model = QStandardItemModel()
            self.transaction_model.setHorizontalHeaderLabels(['Dátum', 'Partner', 'Összeg', 'Kategóriák'])
            self.ui.MultbeliOutput.setModel(self.transaction_model)
            
            # Set column widths
            self.ui.MultbeliOutput.setColumnWidth(0, 100)
            self.ui.MultbeliOutput.setColumnWidth(1, 150)
            self.ui.MultbeliOutput.setColumnWidth(2, 100)
            self.ui.MultbeliOutput.setColumnWidth(3, 200)
            
            # Add "Összes" option to category filter
            self.ui.MultbeliKategoria.insertItem(0, "Összes")
            self.ui.MultbeliKategoria.setCurrentIndex(0)
            
            # Setup date filters with default values (last 30 days)
            today = QtCore.QDate.currentDate()
            epoch = QtCore.QDate(1970, 1, 1) 
            self.ui.MultbeliDatumTol.setDate(epoch)
            self.ui.MultbeliDatumIg.setDate(today)
            
            # Load all transactions initially
            self.load_all_transactions()
        
        def load_all_transactions(self):
            """Load all transactions into the table"""
            from PyQt6.QtGui import QStandardItem
            
            transactions = self.db_manager.get_all_trans()
            
            self.transaction_model.setRowCount(0)
            
            for trans in sorted(transactions, key=lambda t: t.date, reverse=True):
                date_item = QStandardItem(trans.date.strftime('%Y-%m-%d'))
                partner_item = QStandardItem(trans.from_to)
                amount_item = QStandardItem(f"{trans.money:,.2f} Ft")
                
                # Get category names
                category_names = ', '.join([cat.name for cat in trans.categories])
                categories_item = QStandardItem(category_names)
                
                # Color code based on income/expense
                if trans.money >= 0:
                    amount_item.setForeground(QtGui.QColor('green'))
                else:
                    amount_item.setForeground(QtGui.QColor('red'))
                
                self.transaction_model.appendRow([date_item, partner_item, amount_item, categories_item])
        
        def search_transactions(self):
            """Search and filter transactions based on all filter criteria"""
            from PyQt6.QtGui import QStandardItem
            from datetime import datetime
            
            # Get filter criteria
            category_filter = self.ui.MultbeliKategoria.currentText()
            partner_filter = self.ui.MultbeliPartner.text().strip().lower()
            
            # Get date range
            date_from = self.ui.MultbeliDatumTol.date().toPyDate()
            date_to = self.ui.MultbeliDatumIg.date().toPyDate()
            
            # Get amount range
            amount_min = None
            amount_max = None
            
            try:
                min_text = self.ui.MultbeliOsszegMin.text().strip()
                if min_text:
                    amount_min = float(min_text)
            except ValueError:
                QtWidgets.QMessageBox.warning(self, "Hiba", "Érvénytelen minimum összeg!")
                return
            
            try:
                max_text = self.ui.MultbeliOsszegMax.text().strip()
                if max_text:
                    amount_max = float(max_text)
            except ValueError:
                QtWidgets.QMessageBox.warning(self, "Hiba", "Érvénytelen maximum összeg!")
                return
            
            # Get all transactions
            transactions = self.db_manager.get_all_trans()
            
            # Apply filters
            filtered_transactions = []
            
            for trans in transactions:
                # Date range filter
                if trans.date < date_from or trans.date > date_to:
                    continue
                
                # Category filter
                if category_filter != "Összes":
                    has_category = any(cat.name == category_filter for cat in trans.categories)
                    if not has_category:
                        continue
                
                # Partner search filter (case-insensitive, partial match)
                if partner_filter:
                    if partner_filter not in trans.from_to.lower():
                        continue
                
                # Amount range filter (absolute value)
                abs_amount = abs(trans.money)
                if amount_min is not None and abs_amount < amount_min:
                    continue
                if amount_max is not None and abs_amount > amount_max:
                    continue
                
                filtered_transactions.append(trans)
            
            # Update table
            self.transaction_model.setRowCount(0)
            
            for trans in sorted(filtered_transactions, key=lambda t: t.date, reverse=True):
                date_item = QStandardItem(trans.date.strftime('%Y-%m-%d'))
                partner_item = QStandardItem(trans.from_to)
                amount_item = QStandardItem(f"{trans.money:,.2f} Ft")
                
                # Get category names
                category_names = ', '.join([cat.name for cat in trans.categories])
                categories_item = QStandardItem(category_names)
                
                # Color code based on income/expense
                if trans.money >= 0:
                    amount_item.setForeground(QtGui.QColor('green'))
                else:
                    amount_item.setForeground(QtGui.QColor('red'))
                
                self.transaction_model.appendRow([date_item, partner_item, amount_item, categories_item])
            
            # Show info message if no results
            if len(filtered_transactions) == 0:
                QtWidgets.QMessageBox.information(self, "Nincs találat", 
                    "Nincs a szűrési feltételeknek megfelelő tranzakció.")
        
        def show_all_transactions(self):
            """Clear all filters and show all transactions"""
            from datetime import datetime
            
            # Reset category filter
            self.ui.MultbeliKategoria.setCurrentIndex(0)  # "Összes"
            
            # Reset partner search
            self.ui.MultbeliPartner.clear()
            
            # Reset amount filters
            self.ui.MultbeliOsszegMin.clear()
            self.ui.MultbeliOsszegMax.clear()
            
            # Reset date filters to show all dates
            # Set to a very wide range to capture all transactions
            transactions = self.db_manager.get_all_trans()
            if transactions:
                # Find earliest and latest dates
                dates = [t.date for t in transactions]
                earliest = min(dates)
                latest = max(dates)
                
                self.ui.MultbeliDatumTol.setDate(QtCore.QDate(earliest.year, earliest.month, earliest.day))
                self.ui.MultbeliDatumIg.setDate(QtCore.QDate(latest.year, latest.month, latest.day))
            else:
                # Default to today if no transactions
                today = QtCore.QDate.currentDate()
                self.ui.MultbeliDatumTol.setDate(today.addDays(-30))
                self.ui.MultbeliDatumIg.setDate(today)
            
            # Reload all transactions
            self.load_all_transactions()

        def befektetesek_kalkulator(self):
            """Calculate investment returns based on risk and time period"""
            try:
                # Get investment amount
                osszeg_str = self.ui.BefektetesekOsszeg.text()
                if not osszeg_str:
                    QtWidgets.QMessageBox.warning(self, "Hiba", "Kérlek, add meg a befektetési összeget!")
                    return
                
                osszeg = float(osszeg_str)
                
                # Check risk level
                risk = None
                expected_return = 0
                if self.ui.BefektetesekAlacsony.isChecked():
                    risk = "Alacsony"
                    expected_return = 0.03  # 3% annual return
                elif self.ui.BefektetesekKozepes.isChecked():
                    risk = "Közepes"
                    expected_return = 0.07  # 7% annual return
                elif self.ui.BefektetesekMagas.isChecked():
                    risk = "Magas"
                    expected_return = 0.12  # 12% annual return
                else:
                    QtWidgets.QMessageBox.warning(self, "Hiba", "Kérlek, válassz kockázati szintet!")
                    return
                
                # Check time period
                time_period = None
                years = 0
                if self.ui.BefektetesekRovid.isChecked():
                    time_period = "Rövid"
                    years = 1
                elif self.ui.BefektetesekKozepes2.isChecked():
                    time_period = "Közepes"
                    years = 3
                elif self.ui.BefektetesekHosszu.isChecked():
                    time_period = "Hosszú"
                    years = 5
                else:
                    QtWidgets.QMessageBox.warning(self, "Hiba", "Kérlek, válassz időtávot!")
                    return
                
                # Calculate compound interest
                final_amount = osszeg * ((1 + expected_return) ** years)
                profit = final_amount - osszeg
                
                # Display results
                result_text = f"""Befektetési kalkuláció:
                
Befektetett összeg: {osszeg:,.0f} Ft
Kockázat: {risk} ({expected_return*100:.0f}% éves hozam)
Időtáv: {time_period} ({years} év)

Várható végösszeg: {final_amount:,.0f} Ft
Várható profit: {profit:,.0f} Ft"""
                
                self.ui.BefektetesekKimenet.setText(result_text)
                self.ui.BefektetesekKimenet.setStyleSheet("color: green; font-weight: bold;")
                
            except ValueError:
                QtWidgets.QMessageBox.warning(self, "Hiba", "Érvénytelen összeg!")
            except Exception as e:
                QtWidgets.QMessageBox.critical(self, "Hiba", f"Hiba történt: {str(e)}")


        # ---- Félretétel kezelése ----
        def load_savings_list(self):
            """Betölti az adatbázisból a félretett tételeket és megjeleníti a listában."""
            try:
                self.ui.FelretetelLista.clear()
                items = self.db_manager.get_savings_as_list()
                for sid, text in items:
                    item = QtWidgets.QListWidgetItem(text)
                    item.setData(QtCore.Qt.ItemDataRole.UserRole, sid)
                    self.ui.FelretetelLista.addItem(item)
            except Exception as e:
                QtWidgets.QMessageBox.critical(self, "Hiba", f"Nem sikerült betölteni a félretett tételeket: {e}")

        def add_saving(self):
            """Ment egy új félretételt az adatbázisba és frissíti a listát."""
            osszeg_str = self.ui.FelretetelOsszeg.text().strip()
            try:
                osszeg = float(osszeg_str)
            except ValueError:
                QtWidgets.QMessageBox.warning(self, "Hiba", "Kérlek, számot adj meg összegnek!")
                return

            try:
                # get selected category (if any)
                kategoria_name = self.ui.FelretetelKategoria.currentText()
                category_obj = None
                if kategoria_name:
                    cats = self.db_manager.get_all_cat()
                    category_obj = next((c for c in cats if c.name == kategoria_name), None)

                self.db_manager.save_savings(osszeg, category=category_obj)
                self.load_savings_list()
                self.ui.FelretetelOsszeg.clear()
                self.update_balance()
                QtWidgets.QMessageBox.information(self, "Siker", "Félretett összeg mentve.")
            except Exception as e:
                QtWidgets.QMessageBox.critical(self, "Hiba", f"Nem sikerült menteni: {e}")

        def delete_saving(self):
            """Törli a kiválasztott félretételt az adatbázisból."""
            item = self.ui.FelretetelLista.currentItem()
            if not item:
                QtWidgets.QMessageBox.information(self, "Info", "Nincs kiválasztva tétel.")
                return

            sid = item.data(QtCore.Qt.ItemDataRole.UserRole)
            try:
                # import Savings model locally to avoid circulars
                from db_manager import Savings
                saving_obj = self.db_manager.session.query(Savings).filter_by(id=sid).first()
                if saving_obj:
                    self.db_manager.del_savings(saving_obj)
                    self.load_savings_list()
                    self.update_balance()
                    QtWidgets.QMessageBox.information(self, "Siker", "Félretétel törölve.")
                else:
                    QtWidgets.QMessageBox.warning(self, "Hiba", "A kiválasztott tétel nem található.")
            except Exception as e:
                QtWidgets.QMessageBox.critical(self, "Hiba", f"Törlés sikertelen: {e}")



    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()  
    window.show()          
    sys.exit(app.exec())